//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracSatis.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Admin
    {
        public byte AdminID { get; set; }
        public string AdminKAD { get; set; }
        public string AdminSIFRE { get; set; }
    }
}
