//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracSatis.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Blockchain
    {
        public byte BlockID { get; set; }
        public string MusteriName { get; set; }
        public string UrunMarka { get; set; }
        public string UrunModel { get; set; }
        public Nullable<int> UrunFiyat { get; set; }
        public string PreviousHash { get; set; }
        public string Hash { get; set; }
    }
}
