//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AracSatis.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Arac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Arac()
        {
            this.Tbl_Satis = new HashSet<Tbl_Satis>();
        }
    
        public int AracID { get; set; }
        public string AracPLAKA { get; set; }
        public string AracMODEL { get; set; }
        public string AracMARKA { get; set; }
        public string AracKM { get; set; }
        public string AracYIL { get; set; }
        public string AracSehir { get; set; }
        public Nullable<int> Ilan { get; set; }
        public Nullable<int> Kategori { get; set; }
        public Nullable<int> AracFIYAT { get; set; }
        public string AracIMG { get; set; }
    
        public virtual Tbl_Ilan Tbl_Ilan { get; set; }
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Satis> Tbl_Satis { get; set; }
    }
}
